# Raspberry Pi DMX Light Show Configuration

# Audio Input Settings
audio:
  device_name: "hw:1,0"  # Direct ALSA device (change to match your aplay -l output)
  sample_rate: 44100
  buffer_size: 2048  # Increased for Raspberry Pi stability
  input_channels: 1  # Changed to 1 for better device compatibility

# DMX Settings
dmx:
  interface: "/dev/ttyUSB0"  # DMX USB interface device
  universe: 1
  refresh_rate: 30  # Hz

# Light Fixtures
lights:
  par_lights:
    - name: "Par Light 1"
      dmx_address: 1
      channels:
        master_dimmer: 1    # CH1: Total dimming
        red: 2              # CH2: Red Dimming
        green: 3            # CH3: Green Dimming
        blue: 4             # CH4: Blue Dimming
        white: 5            # CH5: White Dimming
        strobe: 6           # CH6: Total strobe
        macro: 7            # CH7: Macro Function
        function_speed: 8   # CH8: Function speed
        light_strip: 9      # CH9: Light strip effect
        strip_speed: 10     # CH10: Light strip speed
    - name: "Par Light 2"
      dmx_address: 11
      channels:
        master_dimmer: 11   # CH1: Total dimming
        red: 12             # CH2: Red Dimming
        green: 13           # CH3: Green Dimming
        blue: 14            # CH4: Blue Dimming
        white: 15           # CH5: White Dimming
        strobe: 16          # CH6: Total strobe
        macro: 17           # CH7: Macro Function
        function_speed: 18  # CH8: Function speed
        light_strip: 19     # CH9: Light strip effect
        strip_speed: 20     # CH10: Light strip speed
    - name: "Par Light 3"
      dmx_address: 21
      channels:
        master_dimmer: 21   # CH1: Total dimming
        red: 22             # CH2: Red Dimming
        green: 23           # CH3: Green Dimming
        blue: 24            # CH4: Blue Dimming
        white: 25           # CH5: White Dimming
        strobe: 26          # CH6: Total strobe
        macro: 27           # CH7: Macro Function
        function_speed: 28  # CH8: Function speed
        light_strip: 29     # CH9: Light strip effect
        strip_speed: 30     # CH10: Light strip speed
    - name: "Par Light 4"
      dmx_address: 31
      channels:
        master_dimmer: 31   # CH1: Total dimming
        red: 32             # CH2: Red Dimming
        green: 33           # CH3: Green Dimming
        blue: 34            # CH4: Blue Dimming
        white: 35           # CH5: White Dimming
        strobe: 36          # CH6: Total strobe
        macro: 37           # CH7: Macro Function
        function_speed: 38  # CH8: Function speed
        light_strip: 39     # CH9: Light strip effect
        strip_speed: 40     # CH10: Light strip speed

# Audio Processing
audio_processing:
  # Beat detection parameters
  beat_detection:
    onset_threshold: 0.15  # Lowered for better sensitivity
    min_tempo: 60
    max_tempo: 200
    hop_length: 512
    
  # Frequency analysis
  frequency_bands:
    bass: [20, 250]      # Hz
    mid: [250, 4000]     # Hz
    treble: [4000, 20000] # Hz
    
  # Volume analysis
  volume:
    smoothing_factor: 0.7
    gain: 2.0
    noise_floor: 0.01

# Light Effects
effects:
  # Color palettes for different moods
  color_palettes:
    energetic: 
      - [255, 0, 0]    # Red
      - [0, 255, 0]    # Green
      - [0, 0, 255]    # Blue
      - [255, 255, 0]  # Yellow
      - [255, 0, 255]  # Magenta
      - [0, 255, 255]  # Cyan
    
    calm:
      - [100, 150, 255] # Soft blue
      - [150, 100, 255] # Soft purple
      - [255, 150, 100] # Soft orange
      - [100, 255, 150] # Soft green
    
    warm:
      - [255, 100, 0]   # Orange
      - [255, 150, 0]   # Amber
      - [255, 200, 100] # Warm white
      - [255, 0, 50]    # Red-orange

  # Effect parameters
  transition_speed: 0.8
  intensity_multiplier: 0.9
  beat_response_strength: 1.2
  color_change_probability: 0.1

# Lighting Configuration Modes
lighting_modes:
  mode_1:
    name: "Classic Auto"
    description: "Original auto-reactive lighting with frequency mapping"
    effect_mode: "auto"
    palette: "energetic"
    transition_speed: 0.8
    beat_response_strength: 1.2
    color_change_probability: 0.1
    intensity_multiplier: 0.9
    
  mode_2:
    name: "Ping Pong Wave"
    description: "Sequential light ping pong effect with smooth color cycling"
    effect_mode: "ping_pong"
    palette: "energetic"
    transition_speed: 0.6
    beat_response_strength: 1.5
    color_change_probability: 0.3
    intensity_multiplier: 1.0
    ping_pong_speed: 2.0  # Speed multiplier for ping pong effect
    
  mode_3:
    name: "Rapid Fade"
    description: "Rapid color transitions with smooth fade in/out effects"
    effect_mode: "flash_storm"
    palette: "energetic"
    transition_speed: 0.9
    beat_response_strength: 1.5
    color_change_probability: 0.5
    intensity_multiplier: 1.1
    flash_intensity: 1.5  # Intensity boost on beats (no strobing)

# System Settings
system:
  debug: true
  log_level: "INFO"
  performance_monitoring: true

